FROM hashicorp/terraform as terraform


FROM python:3.6.5-alpine as python
MAINTAINER Ales Kotnik <ales.kotnik@gmail.com>

# Note: Latest version of kubectl may be found at:
# https://aur.archlinux.org/packages/kubectl-bin/
ENV KUBE_LATEST_VERSION="v1.11.5"
# Note: Latest version of helm may be found at:
# https://github.com/kubernetes/helm/releases
ENV HELM_VERSION="v2.12.0"
ENV KOPS_VERSION="1.11.0-beta.1"
ENV TERRAFORM_VERSION=0.11.11


COPY --from=terraform /bin/terraform /bin

RUN apk update && \
    apk add \
        ca-certificates \
        curl \
        git \
        vim \
        openssh \
        openssl \
        groff \
        bash \
        jq \
        less \
        bind-tools && \
    curl -o /usr/local/bin/kops --location --silent --show-error https://github.com/kubernetes/kops/releases/download/${KOPS_VERSION}/kops-linux-amd64 \
    && chmod +x /usr/local/bin/kops && \
    curl -LSs https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz | tar -xzO linux-amd64/helm > /usr/local/bin/helm \
    && chmod +x /usr/local/bin/helm && \
    curl -o /usr/local/bin/kubectl -LSs https://storage.googleapis.com/kubernetes-release/release/${KUBE_LATEST_VERSION}/bin/linux/amd64/kubectl  \
    && chmod +x /usr/local/bin/kubectl && \
    pip install --upgrade pip && \
    pip install --upgrade awscli==1.16.60

WORKDIR /workdir
ENTRYPOINT "bash"